#!/usr/bin/python
# coding: utf-8


from __future__ import absolute_import, unicode_literals


if __name__ == '__main__':
    from backend.application import main
    main()
else:
    from backend.server import app as application
