#!/bin/sh

# Stop on unintialized variable usage
set -u

# Stop on first error
set -e

function print_help() {
    echo "Usage: deploy-bus-time-database."
}

function print_unknown_args() {
    echo "Unknown arguments specified."
    print_help
}

# Parse args
while [ $# -gt 0 ];
do
    case "$1" in
        -h|--help)  print_help;
                    exit;;
        *)          print_unknown_args;
                    exit;;
    esac
    shift
done

# Stop web, deploy version, run web
heroku maintenance:on
heroku ps:scale web=0
heroku run python application --deploy-version
heroku ps:scale web=1
heroku maintenance:off
